language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-21.1.2
  - android-21
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
before_install:
- chmod +x gradlew
- chmod +x ./scripts/upload.sh
- chmod +x ./scripts/find_version.rb
script:
- ./gradlew build check
branches:
  only:
  - develop
env:
  global:
  - APPNAME="Android-Template"
  - secure: FPzpC29lfgEnQO2DJGWEDlOkTyKBlLmtbqMFVtDSe3gUYUAcZKS8FG8Quxvxt08Mfx/cYJertUyaIBJgHvLs7OYueApjxPBSzEjQgNC1+66fxrsq0NBZGp8tGvcEPUyjHrDIw5kDsbB3gnSyK1k1PjX4vIAWxBsKJoo8UEW5002TK1ZWOWddCqq7LjppHKvaMOwD27b+JZiiMnm5jYMMHv0+B5hLUe1O1am2zZoPwIH1hBkzPKgHddHkj2vREqeKQ+JVVcb4oxswOsG33ci6amIFC50UM5DVGrSlbU5BF9dzslbooJoMdthvSVslbDBwFGx0O6cmIJelZYqdb6ddHhldCz8X7veKhWbnTF4gAyeJK5uTa7SRYWsn0fNSxKSmyX18IFXAHqA01lgxXSRp3vmhK5hXVp+E4/+24jabKpYGFL6plyxIRfoD+rmzElPOo6A6YXxlNiKxxBjln8hB60uYqIn4S8r6+odR7Kv9jLYMYXIex+8WhIHeagzTBedxWUXb4cWzSj5UHDF9lYpvJ+mJNZPOINmM0HuHhee4gAEXpdEKq/Qa471y4H9onuvGMY0YxLXjbzWmB46O4Yt/5tLR+FT+58kWgomgqnDUVYOb22ntk2/r2rRIXVGjMXn02voqwMHDt2UpzITe7OwmLyTotkDkeawRXwBmFpT/muY=
  - secure: onV9+YlXNbSYEkRjnJ9kcV1tZZl0HbUzWLZBTQ3s+dO9tMON1PF9UNCt0h6fm99HjYFDNLL60mZt6PiUdgKoG1oLZikzVKxOb0XoCjJlVco6RrJS27Vqx1f/3IqD1M9WXSctcjF1p+gDnHFCXVcp92X3zzCvBFZDjnflvGGhhQWQ+tLSzeiAtTYs9SyouqMvQ/cSPmB+yh+I92ZoZrh8AaZgvqWFR9TZSt5bAqV0Ygr4obiET9W4d6EPviD3mKFGkV7Ii+gev7QgJr1YUPjZGNRGfGB8yitOYphZ/go28fqmFenRCq9e2zmCU8SrP6SXSIXJB8lSi36TnZ560yHEJrrbGV5oeuwUCHbIaPKoSwEuctH4N1EfTgesxH6NAUhKVB2MvuLAGLVwanHfDu5862dLYoA5jhxNKps9ZZZ7wAHaKvS/B3BCwQ4tISAuSAOqrJYq84y8rVH0P2o/311xFlEZVTcmj0TenwT0QkW+tYXsWkc4a84kpGi8wygwXSwAC4Mviffpv96tdqdb6MWgaE7hujaOUuBuD0mLL0PjhWdcTIe4jjVpS2F6VLNssVdRjceMRelOH0Zinaf/lv8XSGUuP4ne9L192w0RcPnmcccvHkGi7DloQi9BHF4s0APO7QZMb4IGs9g89ScOcUfLjHpR8LMBiwyyAoSqb9dIcnA=
after_success:
- ./scripts/upload.sh
notifications:
  email:
    recipients:
    on_success: always
    on_failure: always
